kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      # crio stores containers in /var/run/containers/storage
      - hostPath: /home/runner/.local/share/containers
        containerPath: /var/run/containers
