# We need to run our pods with GID of 0 (and random UID), the way OpenShift would.
# In current Kubernetes, that requires a 3rd-party mutating webhook, because
# https://kubernetes.io/docs/concepts/security/pod-security-policy got removed.

# > K-Rail, Kyverno, and OPA/Gatekeeper are all well-known, and each has its fans.
# https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

# This attempts to fake the restricted-v2 OCC from OpenShift for labeled namespaces
# c.f. https://kyverno.io/docs/writing-policies/mutate/

# Kubernetes disallows changes to certain fields in resources including name, namespace, uid, kind, and apiVersion,
# therefore you cannot use Kyverno policy to effect any of these fields either during admission or once a resource has been persisted.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: fake-restricted-v2
spec:
  rules:
    - name: set-container-securityContext
      match:
        any:
          - resources:
              kinds:
                - Pod
              # https://kyverno.io/docs/writing-policies/match-exclude/#match-deployments-in-namespaces-using-labels
              namespaceSelector:
                matchExpressions:
                  - key: fake-scc
                    operator: In
                    values:
                      - fake-restricted-v2
      context:
        # https://jmespath.org/specification.html#to-number
        # https://kyverno.io/docs/writing-policies/jmespath/#random
        - name: randomuid
          variable:
            jmesPath: to_number(random('[1-9][0-9]{6}'))
      mutate:
        patchStrategicMerge:
          spec:
            # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
            securityContext:
              runAsUser: "{{randomuid}}"
              runAsGroup: 0
              fsGroup: 100
              supplementalGroups: [ "{{randomuid}}" ]


#export IMAGE_TAG=main_efe90c2ca935875bc6aa5b7653c42c77d14b419b
#export IMAGE_REGISTRY=ghcr.io/jiridanek/notebooks/workbench-images
#python3 ci/cached-builds/make_test.py --target jupyter-minimal-ubi9-python-3.11
