---
name: Update Trivy vulnerabilities DB
"on":
  schedule:
    - cron: "0 0 * * *" # at 00:00
  workflow_dispatch:
jobs:
  update-trivy-vulns-db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      # https://trivy.dev/v0.40/docs/vulnerability/db/
      - name: ""
        run: |
          docker run --rm \
              -v trivy-vulns-db:/var/run/docker.sock \
              -v ${REPORT_FOLDER}:/report \
              docker.io/aquasec/trivy:$TRIVY_VERSION \
                $SCAN_TYPE \
                $SCAN_ARGS \
                --scanners vuln --ignore-unfixed \
                --exit-code 0 --timeout 30m \
                --format template --template "@/report/$REPORT_TEMPLATE" -o /report/$REPORT_FILE \
                $SCAN_TARGET

          cat $REPORT_FOLDER/$REPORT_FILE >> $GITHUB_STEP_SUMMARY